import 'dart:io';

import 'package:flutter_obfuscator/src/crypto/native_key_channel_generator.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  late Directory tempDir;

  setUp(() {
    tempDir =
        Directory.systemTemp.createTempSync('native_key_channel_gen_test_');
  });

  tearDown(() {
    tempDir.deleteSync(recursive: true);
  });

  test('writes native_key_channel.g.dart with the expected MethodChannel API',
      () {
    NativeKeyChannelGenerator.write(projectRoot: tempDir.path);

    final file = File(p.join(
      tempDir.path,
      'lib',
      'flutter_obfuscator',
      'native_key_channel.g.dart',
    ));
    expect(file.existsSync(), isTrue);

    final source = file.readAsStringSync();
    expect(source, contains("MethodChannel('flutter_obfuscator/key')"));
    expect(source, contains('static Future<List<int>> fetchKey()'));
    expect(source, contains('static Future<bool> isTraced()'));
    expect(source, contains('// GENERATED BY flutter_obfuscator. DO NOT EDIT.'));
  });

  test('is idempotent — re-running overwrites rather than appending', () {
    NativeKeyChannelGenerator.write(projectRoot: tempDir.path);
    NativeKeyChannelGenerator.write(projectRoot: tempDir.path);

    final file = File(p.join(
      tempDir.path,
      'lib',
      'flutter_obfuscator',
      'native_key_channel.g.dart',
    ));
    final occurrences =
        'class NativeKeyChannel'.allMatches(file.readAsStringSync()).length;
    expect(occurrences, 1);
  });
}
