import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

/// Writes `lib/flutter_obfuscator/strings.g.dart`, the runtime table
/// `StringLiteralObfuscator` rewrote call sites to reference.
///
/// This intentionally does *not* reuse `SecretVault`'s AES-GCM machinery:
/// the values here are ordinary UI text/log messages/URLs, not secrets,
/// so a lightweight XOR + base64 encoding is all that's needed to defeat
/// a plain `strings`/grep pass — see the generated file's own doc
/// comment for the exact limitation.
class StringVaultGenerator {
  static void write({
    required String projectRoot,
    required List<String> literalValues,
    required List<int> xorKey,
  }) {
    final dir = Directory(p.join(projectRoot, 'lib', 'flutter_obfuscator'));
    dir.createSync(recursive: true);
    File(p.join(dir.path, 'strings.g.dart'))
        .writeAsStringSync(_source(literalValues, xorKey));
  }

  static String _source(List<String> literalValues, List<int> xorKey) {
    final buffer = StringBuffer();
    buffer.writeln('// GENERATED BY flutter_obfuscator. DO NOT EDIT.');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln();
    buffer.writeln("import 'dart:convert';");
    buffer.writeln();
    buffer.writeln('/// Runtime table for string literals flutter_obfuscator');
    buffer.writeln('/// moved out of the Dart snapshot (v9).');
    buffer.writeln('///');
    buffer.writeln(
        '/// v9 limitation: encoded with XOR + base64, not encrypted —');
    buffer.writeln(
        '/// this defeats a plain `strings`/grep static scan of a built');
    buffer.writeln(
        '/// artifact, but the key ships in this same file, so it does not');
    buffer.writeln(
        '/// stop a reverse engineer who decompiles and runs the decode');
    buffer.writeln(
        '/// logic themselves. Use `SecretVault` (real AES-GCM encryption)');
    buffer.writeln('/// for anything that actually needs to stay secret.');
    buffer.writeln('class _StringVault {');
    buffer.writeln('  static const List<int> _key = [${xorKey.join(', ')}];');
    buffer.writeln();
    buffer.writeln('  static const List<String> _table = [');
    for (final value in literalValues) {
      buffer.writeln("    '${_encode(value, xorKey)}',");
    }
    buffer.writeln('  ];');
    buffer.writeln();
    buffer.writeln('  static final List<String?> _cache =');
    buffer.writeln('      List<String?>.filled(_table.length, null);');
    buffer.writeln();
    buffer.writeln('  static String get(int index) {');
    buffer.writeln('    final cached = _cache[index];');
    buffer.writeln('    if (cached != null) return cached;');
    buffer.writeln('    final encoded = base64.decode(_table[index]);');
    buffer.writeln('    final decoded = List<int>.generate(');
    buffer.writeln('      encoded.length,');
    buffer.writeln('      (i) => encoded[i] ^ _key[i % _key.length],');
    buffer.writeln('    );');
    buffer.writeln('    final value = utf8.decode(decoded);');
    buffer.writeln('    _cache[index] = value;');
    buffer.writeln('    return value;');
    buffer.writeln('  }');
    buffer.writeln('}');
    buffer.writeln();
    buffer
        .writeln('/// Looks up string literal [index] in the generated table.');
    buffer.writeln('String obfS(int index) => _StringVault.get(index);');
    return buffer.toString();
  }

  static String _encode(String value, List<int> xorKey) {
    final bytes = utf8.encode(value);
    final encoded = List<int>.generate(
      bytes.length,
      (i) => bytes[i] ^ xorKey[i % xorKey.length],
    );
    return base64.encode(encoded);
  }
}
