import 'dart:io';

import 'package:path/path.dart' as p;

import '../config/cert_pinning_config.dart';
import 'native_injection_result.dart';

/// Generates the Android half of v5 certificate pinning: a declarative
/// `network_security_config.xml` `<pin-set>` per host, wired into
/// `AndroidManifest.xml` via `android:networkSecurityConfig`.
///
/// This is a defense-in-depth layer alongside the Dart `PinnedHttpClient`
/// (see [PinnedHttpClientGenerator]) — Android enforces this config for
/// `HttpsURLConnection`, OkHttp, and `WebView` traffic without any Dart
/// code change, so it also covers plugins and WebViews that don't go
/// through your own HTTP client. It uses the same SHA-256 SPKI pins as
/// the Dart layer.
///
/// There's no iOS equivalent: App Transport Security has no declarative
/// SPKI pin-set without a third-party library, so iOS relies on the Dart
/// layer alone.
///
/// Only one `network_security_config.xml` can be active per app, so a
/// manifest that already sets `android:networkSecurityConfig` is left
/// untouched and reported as skipped, same as [AndroidNdkKeyGenerator]'s
/// `externalNativeBuild` skip.
class AndroidNetworkSecurityConfigGenerator {
  static const _manifestAttribute =
      'android:networkSecurityConfig="@xml/network_security_config"';

  static NativeInjectionResult generate({
    required String projectRoot,
    required CertPinningConfig config,
  }) {
    final manifestFile = File(p.join(
        projectRoot, 'android', 'app', 'src', 'main', 'AndroidManifest.xml'));
    if (!manifestFile.existsSync()) {
      return NativeInjectionResult(
        platform: 'android',
        applied: false,
        reason: 'no android/app/src/main/AndroidManifest.xml found — is '
            'this an Android-enabled Flutter project?',
      );
    }

    final source = manifestFile.readAsStringSync();
    if (RegExp(r'android:networkSecurityConfig\s*=').hasMatch(source) &&
        !source.contains(_manifestAttribute)) {
      return NativeInjectionResult(
        platform: 'android',
        applied: false,
        entryPointPath: manifestFile.path,
        reason: '${manifestFile.path} already declares '
            'android:networkSecurityConfig — Android only supports one '
            'network security config per app, so flutter_obfuscator left '
            'it alone. Merge the generated pin-set at '
            'android/app/src/main/res/xml/network_security_config.xml '
            'into your existing config manually.',
      );
    }

    final xmlDir = Directory(
        p.join(projectRoot, 'android', 'app', 'src', 'main', 'res', 'xml'));
    xmlDir.createSync(recursive: true);
    File(p.join(xmlDir.path, 'network_security_config.xml'))
        .writeAsStringSync(_xmlSource(config));

    if (source.contains(_manifestAttribute)) {
      // Already wired from a previous run.
      return NativeInjectionResult(
        platform: 'android',
        applied: true,
        entryPointPath: manifestFile.path,
      );
    }

    final appTagMatch = RegExp(r'<application\b').firstMatch(source);
    if (appTagMatch == null) {
      return NativeInjectionResult(
        platform: 'android',
        applied: false,
        entryPointPath: manifestFile.path,
        reason: 'no <application> tag found in ${manifestFile.path} — the '
            'pin-set was generated, but you need to add '
            '$_manifestAttribute to <application> yourself',
      );
    }

    final insertAt = appTagMatch.end;
    final updated = source.replaceRange(
        insertAt, insertAt, '\n        $_manifestAttribute');
    manifestFile.writeAsStringSync(updated);

    return NativeInjectionResult(
      platform: 'android',
      applied: true,
      entryPointPath: manifestFile.path,
    );
  }

  static String _xmlSource(CertPinningConfig config) {
    final buffer = StringBuffer();
    buffer.writeln('<?xml version="1.0" encoding="utf-8"?>');
    buffer.writeln('<!-- GENERATED BY flutter_obfuscator. DO NOT EDIT. -->');
    buffer.writeln('<network-security-config>');
    for (final host in config.hosts) {
      buffer.writeln('    <domain-config>');
      buffer.writeln('        <domain includeSubdomains="true">${host.host}'
          '</domain>');
      buffer.writeln('        <pin-set>');
      for (final pin in host.spkiSha256) {
        buffer.writeln('            <pin digest="SHA-256">$pin</pin>');
      }
      buffer.writeln('        </pin-set>');
      buffer.writeln('    </domain-config>');
    }
    buffer.writeln('</network-security-config>');
    return buffer.toString();
  }
}
