import 'dart:io';
import 'dart:math';

import 'package:path/path.dart' as p;

import '../crypto/key_split_plan.dart';
import 'android_main_activity_injector.dart';
import 'native_injection_result.dart';

/// Generates the Android half of the v2 native key channel: a Kotlin
/// object holding a split/XOR-obfuscated copy of the vault key plus a
/// `FlutterPlugin` exposing it over the `flutter_obfuscator/key`
/// MethodChannel, and injects its registration into `MainActivity.kt`.
///
/// Only Kotlin `MainActivity` files matching the standard `flutter
/// create` shape are patched; anything else is reported as skipped with
/// instructions rather than risking a broken build.
///
/// [AndroidNdkKeyGenerator] (v3) reuses [AndroidMainActivityInjector] for
/// the identical `MainActivity.kt` wiring, but generates a JNI-backed
/// `ObfuscatorKeyPlugin` instead of this pure-Kotlin one.
class AndroidNativeKeyGenerator {
  static NativeInjectionResult generate({
    required String projectRoot,
    required List<int> keyBytes,
    Random? random,
  }) {
    final located = AndroidMainActivityInjector.locate(projectRoot);
    if (located.location == null) {
      return NativeInjectionResult(
        platform: 'android',
        applied: false,
        reason: located.reason,
      );
    }
    final mainActivityFile = located.location!.file;
    final packageName = located.location!.packageName;

    final pluginFile = File(
        p.join(p.dirname(mainActivityFile.path), 'ObfuscatorKeyPlugin.kt'));
    pluginFile.writeAsStringSync(
      _pluginSource(packageName, keyBytes, random: random),
    );

    final injected =
        AndroidMainActivityInjector.inject(mainActivityFile.readAsStringSync());
    if (injected == null) {
      return NativeInjectionResult(
        platform: 'android',
        applied: false,
        entryPointPath: mainActivityFile.path,
        pluginFilePath: pluginFile.path,
        reason: '${mainActivityFile.path} doesn\'t match the standard '
            '`flutter create` MainActivity shape (class MainActivity : '
            'FlutterActivity() { ... }) — ObfuscatorKeyPlugin.kt was '
            'generated, but you need to register it yourself: override '
            'configureFlutterEngine and call '
            'flutterEngine.plugins.add(ObfuscatorKeyPlugin())',
      );
    }
    mainActivityFile.writeAsStringSync(injected);

    return NativeInjectionResult(
      platform: 'android',
      applied: true,
      entryPointPath: mainActivityFile.path,
      pluginFilePath: pluginFile.path,
    );
  }

  static String _pluginSource(
    String packageName,
    List<int> keyBytes, {
    Random? random,
  }) {
    final plan = KeySplitPlan.derive(keyBytes, random: random);

    final buffer = StringBuffer();
    buffer.writeln('// GENERATED BY flutter_obfuscator. DO NOT EDIT.');
    buffer.writeln('package $packageName');
    buffer.writeln();
    buffer.writeln('import io.flutter.embedding.engine.plugins.FlutterPlugin');
    buffer.writeln('import io.flutter.plugin.common.MethodCall');
    buffer.writeln('import io.flutter.plugin.common.MethodChannel');
    buffer.writeln('import java.io.File');
    buffer.writeln();
    buffer.writeln('private object ObfKeyMaterial {');

    final chunkNames = <String>[];
    final padNames = <String>[];
    for (final chunk in plan.chunks) {
      final chunkName = '_${chunk.name}Xor';
      final padName = '_${chunk.name}Pad';
      chunkNames.add(chunkName);
      padNames.add(padName);
      buffer.writeln(
          '    private val $chunkName = ${_byteArrayLiteral(chunk.xored)}');
      buffer.writeln(
          '    private val $padName = ${_byteArrayLiteral(chunk.pad)}');
    }

    buffer.writeln();
    buffer.writeln('    fun materialize(): ByteArray {');
    buffer.writeln('        val out = ArrayList<Byte>()');
    for (var i = 0; i < chunkNames.length; i++) {
      buffer.writeln('        for (i in ${chunkNames[i]}.indices) {');
      buffer.writeln(
          '            out.add((${chunkNames[i]}[i].toInt() xor ${padNames[i]}[i].toInt()).toByte())');
      buffer.writeln('        }');
    }
    buffer.writeln('        return out.toByteArray()');
    buffer.writeln('    }');
    buffer.writeln('}');
    buffer.writeln();
    buffer.writeln('''
class ObfuscatorKeyPlugin : FlutterPlugin, MethodChannel.MethodCallHandler {
    private lateinit var channel: MethodChannel

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        channel = MethodChannel(binding.binaryMessenger, "flutter_obfuscator/key")
        channel.setMethodCallHandler(this)
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        channel.setMethodCallHandler(null)
    }

    override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
        when (call.method) {
            "getKey" -> result.success(ObfKeyMaterial.materialize())
            "isTraced" -> result.success(isTraced())
            else -> result.notImplemented()
        }
    }

    // TracerPid is nonzero in /proc/self/status whenever a debugger or
    // ptrace-based tool (gdb, Frida) is attached to this process — the
    // same signal most Android anti-debug libraries check.
    private fun isTraced(): Boolean {
        return try {
            File("/proc/self/status").readLines().any { line ->
                line.startsWith("TracerPid:") && line.substringAfter(":").trim() != "0"
            }
        } catch (e: Exception) {
            false
        }
    }
}
''');

    return buffer.toString();
  }

  static String _byteArrayLiteral(List<int> bytes) {
    final literals =
        bytes.map((b) => '0x${b.toRadixString(16).padLeft(2, '0')}.toByte()');
    return 'byteArrayOf(${literals.join(', ')})';
  }
}
