import 'dart:io';
import 'dart:math';

import 'package:path/path.dart' as p;

import '../crypto/key_split_plan.dart';
import 'ios_app_delegate_injector.dart';
import 'native_injection_result.dart';

/// Generates the iOS half of the v2 native key channel: a Swift enum
/// holding a split/XOR-obfuscated copy of the vault key plus a
/// `FlutterPlugin` exposing it over the `flutter_obfuscator/key`
/// MethodChannel, and injects its registration into `AppDelegate.swift`
/// right after `GeneratedPluginRegistrant.register(with: self)`.
///
/// Only the standard `flutter create` AppDelegate shape is patched;
/// anything else is reported as skipped with instructions.
class IosNativeKeyGenerator {
  static NativeInjectionResult generate({
    required String projectRoot,
    required List<int> keyBytes,
    Random? random,
  }) {
    final located = IosAppDelegateInjector.locate(projectRoot);
    if (located.file == null) {
      return NativeInjectionResult(
          platform: 'ios', applied: false, reason: located.reason);
    }
    final appDelegateFile = located.file!;

    final pluginFile = File(
        p.join(p.dirname(appDelegateFile.path), 'ObfuscatorKeyPlugin.swift'));
    pluginFile.writeAsStringSync(_pluginSource(keyBytes, random: random));

    final source = appDelegateFile.readAsStringSync();
    final injected = IosAppDelegateInjector.inject(source);
    if (injected == null) {
      return NativeInjectionResult(
        platform: 'ios',
        applied: false,
        entryPointPath: appDelegateFile.path,
        pluginFilePath: pluginFile.path,
        reason: '${appDelegateFile.path} doesn\'t contain '
            '`GeneratedPluginRegistrant.register(with: self)` in the '
            'standard `flutter create` shape — ObfuscatorKeyPlugin.swift '
            'was generated, but you need to register it yourself: call '
            'ObfuscatorKeyPlugin.register(with: '
            'self.registrar(forPlugin: "ObfuscatorKeyPlugin")!) inside '
            'application(_:didFinishLaunchingWithOptions:)',
      );
    }
    appDelegateFile.writeAsStringSync(injected);

    return NativeInjectionResult(
      platform: 'ios',
      applied: true,
      entryPointPath: appDelegateFile.path,
      pluginFilePath: pluginFile.path,
    );
  }

  static String _pluginSource(List<int> keyBytes, {Random? random}) {
    final plan = KeySplitPlan.derive(keyBytes, random: random);

    final buffer = StringBuffer();
    buffer.writeln('// GENERATED BY flutter_obfuscator. DO NOT EDIT.');
    buffer.writeln('import Flutter');
    buffer.writeln('import Foundation');
    buffer.writeln('import Darwin');
    buffer.writeln();
    buffer.writeln('private enum ObfKeyMaterial {');

    final chunkNames = <String>[];
    final padNames = <String>[];
    for (final chunk in plan.chunks) {
      final chunkName = '_${chunk.name}Xor';
      final padName = '_${chunk.name}Pad';
      chunkNames.add(chunkName);
      padNames.add(padName);
      buffer.writeln(
          '    static let $chunkName: [UInt8] = ${_arrayLiteral(chunk.xored)}');
      buffer.writeln(
          '    static let $padName: [UInt8] = ${_arrayLiteral(chunk.pad)}');
    }

    buffer.writeln();
    buffer.writeln('    static func materialize() -> [UInt8] {');
    buffer.writeln('        var out: [UInt8] = []');
    for (var i = 0; i < chunkNames.length; i++) {
      buffer.writeln('        for i in 0..<${chunkNames[i]}.count {');
      buffer.writeln(
          '            out.append(${chunkNames[i]}[i] ^ ${padNames[i]}[i])');
      buffer.writeln('        }');
    }
    buffer.writeln('        return out');
    buffer.writeln('    }');
    buffer.writeln('}');
    buffer.writeln();
    buffer.writeln('''
final class ObfuscatorKeyPlugin: NSObject, FlutterPlugin {
    static func register(with registrar: FlutterPluginRegistrar) {
        let channel = FlutterMethodChannel(
            name: "flutter_obfuscator/key",
            binaryMessenger: registrar.messenger()
        )
        let instance = ObfuscatorKeyPlugin()
        registrar.addMethodCallDelegate(instance, channel: channel)
    }

    func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        switch call.method {
        case "getKey":
            result(FlutterStandardTypedData(bytes: Data(ObfKeyMaterial.materialize())))
        case "isTraced":
            result(ObfuscatorKeyPlugin.isTraced())
        default:
            result(FlutterMethodNotImplemented)
        }
    }

    // The P_TRACED flag is set on this process's kinfo_proc whenever a
    // debugger or ptrace-based tool (lldb, Frida) is attached.
    private static func isTraced() -> Bool {
        var info = kinfo_proc()
        var mib: [Int32] = [CTL_KERN, KERN_PROC, KERN_PROC_PID, getpid()]
        var size = MemoryLayout<kinfo_proc>.stride
        let result = sysctl(&mib, UInt32(mib.count), &info, &size, nil, 0)
        guard result == 0 else { return false }
        return (info.kp_proc.p_flag & P_TRACED) != 0
    }
}
''');

    return buffer.toString();
  }

  static String _arrayLiteral(List<int> bytes) {
    final literals =
        bytes.map((b) => '0x${b.toRadixString(16).padLeft(2, '0')}');
    return '[${literals.join(', ')}]';
  }
}
