import 'dart:io';

import 'package:path/path.dart' as p;

import '../config/cert_pinning_config.dart';

/// Writes `lib/flutter_obfuscator/pinned_http_client.g.dart` (v5, opt-in):
/// a `dart:io` `HttpClient` that enforces SPKI certificate pinning against
/// the SHA-256 hashes configured under `certificate_pinning.pins` in
/// `obfuscator.yaml`.
///
/// This is the "generate a utility class, you adopt it" pattern (like
/// `SecretVault.init()`), not the "auto-rewrite call sites" pattern used
/// for encrypted assets: Flutter apps reach the network through too many
/// shapes (`dart:io`, `package:http`, `package:dio`, GraphQL clients,
/// WebSockets, WebViews) for a rewriter to reliably find and swap them
/// all. You wire `PinnedHttpClient` in where you construct your own HTTP
/// client — the generated file's doc comment shows the `http` and `dio`
/// adoption points.
class PinnedHttpClientGenerator {
  static void write({
    required String projectRoot,
    required CertPinningConfig config,
  }) {
    final dir = Directory(p.join(projectRoot, 'lib', 'flutter_obfuscator'));
    dir.createSync(recursive: true);
    File(p.join(dir.path, 'pinned_http_client.g.dart'))
        .writeAsStringSync(_source(config));
  }

  static String _source(CertPinningConfig config) {
    final hostEntries = config.hosts.map((h) {
      final pins = h.spkiSha256.map((s) => "'$s'").join(', ');
      return "  _HostPin('${h.host}', [$pins]),";
    }).join('\n');
    final policyLiteral = config.unpinnedHostPolicy == UnpinnedHostPolicy.allow
        ? 'UnpinnedHostPolicy.allow'
        : 'UnpinnedHostPolicy.block';

    return '''
// GENERATED BY flutter_obfuscator. DO NOT EDIT.
// ignore_for_file: type=lint

import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart' as crypto;

/// What [PinnedHttpClient] does with a host that has no configured pin.
/// See `certificate_pinning.unpinned_hosts` in obfuscator.yaml.
enum UnpinnedHostPolicy { block, allow }

class _HostPin {
  const _HostPin(this.host, this.spkiSha256);
  final String host;
  final List<String> spkiSha256;
}

const List<_HostPin> _pinnedHosts = [
$hostEntries
];

const UnpinnedHostPolicy _unpinnedHostPolicy = $policyLiteral;

/// Builds a `dart:io` [HttpClient] that pins the leaf certificate's
/// SHA-256 SPKI (SubjectPublicKeyInfo) hash per host, generated from
/// `certificate_pinning.pins` in obfuscator.yaml. Same pin format as
/// Android's `network_security_config.xml` `<pin-set>` (generated
/// alongside this file, if that layer is also enabled) and RFC 7469
/// HPKP-style `pin-sha256` values.
///
/// ## Adopting it
///
/// This client isn't wired into your code automatically — swap it in
/// wherever you construct your own HTTP client:
///
/// - `dart:io` directly: use `PinnedHttpClient.create()` in place of
///   `HttpClient()`.
/// - `package:http`: `IOClient(PinnedHttpClient.create())` in place of
///   `http.Client()`.
/// - `package:dio`: give `Dio()` an
///   `IOHttpClientAdapter(createHttpClient: PinnedHttpClient.create)`.
///
/// ## How pinning is enforced here, and why that matters
///
/// `dart:io`'s `HttpClient.badCertificateCallback` is only invoked when
/// the platform's normal certificate-chain validation *fails*. For a
/// certificate that chains to any root the OS already trusts — including
/// a malicious or compromised CA, or an enterprise MITM proxy's installed
/// root — validation succeeds and the callback never fires, so pinning
/// would silently do nothing against exactly the attack it exists to
/// stop. To make the callback authoritative for every connection this
/// client makes, it's constructed with
/// `SecurityContext(withTrustedRoots: false)`, which disables the
/// platform trust store for this client (only this client — a plain
/// `HttpClient()` elsewhere in your app is unaffected) so every
/// certificate reaches [_checkCertificate] and is judged solely against
/// the configured pins.
///
/// [_extractSpki] does a minimal DER walk of the leaf certificate to pull
/// out the encoded SubjectPublicKeyInfo (skipping the optional `version`
/// field, then serialNumber/signatureAlgorithm/issuer/validity/subject in
/// order) rather than hashing the whole certificate — `dart:io`'s
/// `X509Certificate` exposes only the full DER (`cert.der`), not the SPKI
/// alone, and there's no `package:asn1lib`-class dependency assumed to be
/// in your app.
///
/// One consequence of disabling the trust store: for a host with no
/// configured pin, `unpinned_hosts: allow` cannot mean "fall back to
/// normal HTTPS validation" — `dart:io` exposes no API to re-run platform
/// chain validation from inside this callback once trusted roots are
/// disabled. `allow` here means "accept any certificate whose validity
/// window covers now," nothing more. If you need real validation for a
/// host, pin it, or route it through a separate, unpinned
/// `HttpClient`/`Dio()` instead of this one.
///
/// ## What this does NOT protect against
///
/// A Frida script (or an on-device instrumentation framework) that hooks
/// `badCertificateCallback` directly, or that hooks OkHttp's
/// `CertificatePinner`/`TrustManager` on Android below the Dart layer,
/// bypasses this outright — this is, in fact, the single most common
/// "SSL pinning bypass" script in circulation. Pair this with the v4
/// tamper-detection layer and Android's `network_security_config.xml`
/// pin-set for defense in depth; treat none of them as sufficient alone.
///
/// Pin rotation and expiry are your responsibility: list a primary pin
/// plus at least one backup for the certificate you'll rotate to, and
/// re-run flutter_obfuscator with updated pins before the current
/// certificate expires.
class PinnedHttpClient {
  PinnedHttpClient._();

  /// `dart:io`'s `HttpClient` only exposes factory constructors, so it
  /// can't be subclassed — this builds and configures a plain
  /// `HttpClient` instance instead.
  static HttpClient create() {
    final client = HttpClient(context: SecurityContext(withTrustedRoots: false));
    client.badCertificateCallback = _checkCertificate;
    return client;
  }

  static bool _checkCertificate(X509Certificate cert, String host, int port) {
    final pins = _lookupPins(host);
    final spki = _extractSpki(cert.der);
    if (pins == null) {
      if (_unpinnedHostPolicy == UnpinnedHostPolicy.allow) {
        final now = DateTime.now();
        return now.isAfter(cert.startValidity) &&
            now.isBefore(cert.endValidity);
      }
      return false;
    }
    if (spki == null) return false;
    final fingerprint = base64Encode(crypto.sha256.convert(spki).bytes);
    return pins.contains(fingerprint);
  }

  static List<String>? _lookupPins(String host) {
    for (final entry in _pinnedHosts) {
      if (entry.host == host) return entry.spkiSha256;
    }
    return null;
  }

  /// Extracts the DER-encoded `subjectPublicKeyInfo` SEQUENCE (tag +
  /// length + value) from an X.509 certificate's full DER encoding, or
  /// `null` if the structure doesn't parse as expected.
  ///
  /// Certificate ::= SEQUENCE { tbsCertificate, signatureAlgorithm,
  /// signatureValue }; tbsCertificate ::= SEQUENCE { [0] version
  /// OPTIONAL, serialNumber, signature, issuer, validity, subject,
  /// subjectPublicKeyInfo, ... }.
  static List<int>? _extractSpki(List<int> certDer) {
    try {
      final cert = _DerReader(certDer).readTlv();
      final tbsCertificate = _DerReader(certDer, cert.contentStart).readTlv();
      final fields = _DerReader(certDer, tbsCertificate.contentStart);

      var field = fields.readTlv();
      if (field.tag == 0xA0) {
        // Optional explicit `[0] version` — skip it, next field is
        // serialNumber.
        field = fields.readTlv();
      }
      fields.readTlv(); // signature (AlgorithmIdentifier)
      fields.readTlv(); // issuer
      fields.readTlv(); // validity
      fields.readTlv(); // subject
      final spki = fields.readTlv(); // subjectPublicKeyInfo
      return certDer.sublist(spki.start, spki.contentEnd);
    } catch (_) {
      return null;
    }
  }
}

class _Tlv {
  _Tlv(this.start, this.tag, this.contentStart, this.contentEnd);
  final int start;
  final int tag;
  final int contentStart;
  final int contentEnd;
}

/// Walks sibling DER TLV (tag-length-value) elements starting at [pos]
/// within [data]. Only decodes tag + length; callers consume `contentEnd`
/// verbatim rather than recursing, which is all pulling `subjectPublicKeyInfo`
/// out of an X.509 certificate needs.
class _DerReader {
  _DerReader(this.data, [this.pos = 0]);
  final List<int> data;
  int pos;

  _Tlv readTlv() {
    final start = pos;
    final tag = data[pos];
    pos++;
    var length = data[pos];
    pos++;
    if (length & 0x80 != 0) {
      final numBytes = length & 0x7F;
      length = 0;
      for (var i = 0; i < numBytes; i++) {
        length = (length << 8) | data[pos];
        pos++;
      }
    }
    final contentStart = pos;
    final contentEnd = pos + length;
    pos = contentEnd;
    return _Tlv(start, tag, contentStart, contentEnd);
  }
}
''';
  }
}
