import 'dart:io';

import 'package:path/path.dart' as p;

import '../crypto/key_strategy.dart';

/// Writes `lib/flutter_obfuscator/tamper_guard.g.dart` (v4, opt-in): a
/// best-effort, dependency-free root/jailbreak/Frida heuristic scanner
/// that `SecretVault`/`AssetVault` consult before decrypting anything,
/// when `tamper_detection.enabled: true` in `obfuscator.yaml`.
///
/// This is a static-analysis-tool countermeasure, not an anti-Frida
/// silver bullet: every check here runs in Dart (when [keyStrategy] is
/// [KeyStrategy.dartSplit]) or is reached via a MethodChannel call (for
/// the native strategies), and both of those are themselves hookable by
/// the exact tool this is trying to detect. It raises the cost of a
/// casual/automated pass; it does not stop a reverse engineer willing to
/// patch out the check itself before it runs.
class TamperGuardGenerator {
  static void write({
    required String projectRoot,
    required KeyStrategy keyStrategy,
  }) {
    final dir = Directory(p.join(projectRoot, 'lib', 'flutter_obfuscator'));
    dir.createSync(recursive: true);
    File(p.join(dir.path, 'tamper_guard.g.dart'))
        .writeAsStringSync(_source(keyStrategy));
  }

  static String _source(KeyStrategy keyStrategy) {
    final isNative = keyStrategy.usesNativeChannel;
    final keyImport = isNative ? "\nimport 'native_key_channel.g.dart';" : '';
    final nativeCheck = isNative
        ? '''
    try {
      if (await NativeKeyChannel.isTraced()) {
        signals.add(const TamperSignal(
          'native_traced',
          'native code reports a debugger/tracer attached to this process',
        ));
      }
    } catch (_) {
      // A missing/unregistered plugin shouldn't crash the scan itself —
      // the other heuristics below still run.
    }
'''
        : '';

    return '''
// GENERATED BY flutter_obfuscator. DO NOT EDIT.
// ignore_for_file: type=lint

import 'dart:io';$keyImport

/// One root/jailbreak/Frida heuristic that fired.
class TamperSignal {
  const TamperSignal(this.id, this.description);
  final String id;
  final String description;

  @override
  String toString() => id;
}

/// Result of a [TamperGuard.scan] pass.
class TamperReport {
  const TamperReport(this.signals);
  final List<TamperSignal> signals;
  bool get suspicious => signals.isNotEmpty;
}

/// Thrown by `SecretVault`/`AssetVault` when `tamper_detection.mode: block`
/// (the default) and [TamperGuard.scan] found something.
class TamperDetectedException implements Exception {
  TamperDetectedException(this.report);
  final TamperReport report;

  @override
  String toString() =>
      'TamperDetectedException: \${report.signals.map((s) => s.id).join(', ')}';
}

/// Best-effort root/jailbreak/Frida heuristics.
///
/// See this file's generator doc comment (`tamper_guard_generator.dart`)
/// for the honest limitation: everything here can itself be hooked or
/// patched by the same class of tool it looks for. Treat this as raising
/// the bar for casual/automated inspection, not as a real anti-tampering
/// control — pair it with certificate pinning and a dedicated RASP
/// product for anything that actually needs to withstand a targeted
/// attacker.
class TamperGuard {
  TamperGuard._();

  static const List<String> _androidRootPaths = [
    '/system/app/Superuser.apk',
    '/sbin/su',
    '/system/bin/su',
    '/system/xbin/su',
    '/data/local/xbin/su',
    '/data/local/bin/su',
    '/system/sd/xbin/su',
    '/system/bin/failsafe/su',
    '/data/local/su',
    '/su/bin/su',
    '/sbin/.magisk',
    '/data/adb/magisk',
  ];

  static const List<String> _iosJailbreakPaths = [
    '/Applications/Cydia.app',
    '/Library/MobileSubstrate/MobileSubstrate.dylib',
    '/bin/bash',
    '/usr/sbin/sshd',
    '/etc/apt',
    '/private/var/lib/apt',
    '/private/var/stash',
    '/Applications/blackra1n.app',
  ];

  static const List<int> _defaultFridaPorts = [27042, 27043];

  static const String _fridaServerPath = '/data/local/tmp/re.frida.server';

  static Future<TamperReport> scan() async {
    final signals = <TamperSignal>[];

    if (Platform.isAndroid) {
      for (final path in _androidRootPaths) {
        if (File(path).existsSync() || Directory(path).existsSync()) {
          signals.add(TamperSignal('root_path', 'root indicator at \$path'));
          break;
        }
      }
      if (File(_fridaServerPath).existsSync()) {
        signals.add(const TamperSignal(
            'frida_server_binary', 'frida-server binary found on device'));
      }
      _scanProcMaps(signals);
    }

    if (Platform.isIOS) {
      for (final path in _iosJailbreakPaths) {
        if (File(path).existsSync() || Directory(path).existsSync()) {
          signals.add(
              TamperSignal('jailbreak_path', 'jailbreak indicator at \$path'));
          break;
        }
      }
    }

    if (Platform.isAndroid || Platform.isIOS) {
      for (final port in _defaultFridaPorts) {
        if (await _portInUse(port)) {
          signals.add(TamperSignal(
              'frida_port', 'default frida-server port \$port is in use'));
          break;
        }
      }
    }
$nativeCheck
    return TamperReport(signals);
  }

  static void _scanProcMaps(List<TamperSignal> signals) {
    try {
      final maps = File('/proc/self/maps').readAsStringSync();
      const needles = ['frida', 'xposed', 'substrate', 'cydia'];
      for (final needle in needles) {
        if (maps.contains(needle)) {
          signals.add(TamperSignal(
              'proc_maps', '/proc/self/maps references "\$needle"'));
          return;
        }
      }
    } catch (_) {
      // /proc/self/maps may be unreadable (SELinux, non-Linux) — that's
      // not itself a signal.
    }
  }

  static Future<bool> _portInUse(int port) async {
    try {
      final socket = await ServerSocket.bind(
        InternetAddress.loopbackIPv4,
        port,
        shared: false,
      ).timeout(const Duration(milliseconds: 300));
      await socket.close();
      return false;
    } catch (_) {
      return true;
    }
  }
}
''';
  }
}
