import 'dart:math';

/// Generates the AES key used by the vaults, plus Dart source that
/// reconstructs it at runtime without ever holding it as a single
/// plaintext constant.
///
/// This is the v1 (Dart-only) key strategy. It raises the bar over a
/// single hardcoded key constant — an attacker has to find and XOR
/// several scattered, innocuously-named chunks instead of grepping one
/// string — but the key material still ships inside the Dart snapshot,
/// so it does not stop a motivated reverse engineer with a decompiler.
/// v2 moves this key material into native code behind a platform channel,
/// which this tool does not implement yet.
class VaultKeyMaterial {
  VaultKeyMaterial._(this.keyBytes, this.generatedSource);

  final List<int> keyBytes;
  final String generatedSource;

  static const int keyLengthBytes = 32;
  static const int _chunkCount = 4;

  static final List<String> _fakeNamePool = [
    'themeFlags',
    'layoutMetrics',
    'featureToggleTable',
    'localeFallbackOrder',
    'gridSpacingUnits',
    'animationCurveSeed',
    'cacheShardTable',
    'retryBackoffTable',
  ];

  factory VaultKeyMaterial.generate({Random? random}) {
    final rnd = random ?? Random.secure();
    final key = List<int>.generate(keyLengthBytes, (_) => rnd.nextInt(256));

    final chunkSize = keyLengthBytes ~/ _chunkCount;
    final pool = List<String>.from(_fakeNamePool)..shuffle(rnd);
    final chunkNames = <String>[];
    final padNames = <String>[];
    final buffer = StringBuffer();

    buffer.writeln('// GENERATED BY flutter_obfuscator. DO NOT EDIT.');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln();
    buffer.writeln('class _ObfKeyMaterial {');

    for (var i = 0; i < _chunkCount; i++) {
      final start = i * chunkSize;
      final end = (i == _chunkCount - 1) ? keyLengthBytes : start + chunkSize;
      final chunk = key.sublist(start, end);
      final pad = List<int>.generate(chunk.length, (_) => rnd.nextInt(256));
      final xored = List<int>.generate(chunk.length, (j) => chunk[j] ^ pad[j]);

      final chunkName = '_${pool[i % pool.length]}Xor';
      final padName = '_${pool[i % pool.length]}Pad';
      chunkNames.add(chunkName);
      padNames.add(padName);

      buffer.writeln('  static const List<int> $chunkName = $xored;');
      buffer.writeln('  static const List<int> $padName = $pad;');
    }

    buffer.writeln();
    buffer.writeln('  static List<int> materialize() {');
    buffer.writeln('    final out = <int>[];');
    for (var i = 0; i < _chunkCount; i++) {
      buffer.writeln('    for (var i = 0; i < ${chunkNames[i]}.length; i++) {');
      buffer.writeln('      out.add(${chunkNames[i]}[i] ^ ${padNames[i]}[i]);');
      buffer.writeln('    }');
    }
    buffer.writeln('    return out;');
    buffer.writeln('  }');
    buffer.writeln('}');

    return VaultKeyMaterial._(key, buffer.toString());
  }
}
