import 'dart:math';

import 'key_split_plan.dart';

/// Generates the AES key used by the vaults, plus Dart source that
/// reconstructs it at runtime without ever holding it as a single
/// plaintext constant.
///
/// This is the v1 (Dart-only) key strategy ([KeyStrategy.dartSplit]). It
/// raises the bar over a single hardcoded key constant — an attacker has
/// to find and XOR several scattered, innocuously-named chunks instead of
/// grepping one string — but the key material still ships inside the
/// Dart snapshot, so it does not stop a motivated reverse engineer with a
/// decompiler, or a Dart-snapshot-aware extraction tool.
///
/// [KeyStrategy.nativeChannel] (v2, see `lib/src/native/`) removes the
/// key from the Dart snapshot entirely instead.
class VaultKeyMaterial {
  VaultKeyMaterial._(this.keyBytes, this.generatedSource);

  final List<int> keyBytes;
  final String generatedSource;

  static const int keyLengthBytes = 32;

  /// [keyBytes] lets a caller reuse an already-generated key (so the same
  /// key is used everywhere in a run) instead of generating a new one.
  factory VaultKeyMaterial.generate({List<int>? keyBytes, Random? random}) {
    final rnd = random ?? Random.secure();
    final key =
        keyBytes ?? generateKeyBytes(lengthBytes: keyLengthBytes, random: rnd);
    final plan = KeySplitPlan.derive(key, random: rnd);

    final buffer = StringBuffer();
    buffer.writeln('// GENERATED BY flutter_obfuscator. DO NOT EDIT.');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln();
    buffer.writeln('class _ObfKeyMaterial {');

    final chunkNames = <String>[];
    final padNames = <String>[];
    for (final chunk in plan.chunks) {
      final chunkName = '_${chunk.name}Xor';
      final padName = '_${chunk.name}Pad';
      chunkNames.add(chunkName);
      padNames.add(padName);
      buffer.writeln('  static const List<int> $chunkName = ${chunk.xored};');
      buffer.writeln('  static const List<int> $padName = ${chunk.pad};');
    }

    buffer.writeln();
    buffer.writeln('  static List<int> materialize() {');
    buffer.writeln('    final out = <int>[];');
    for (var i = 0; i < chunkNames.length; i++) {
      buffer.writeln('    for (var i = 0; i < ${chunkNames[i]}.length; i++) {');
      buffer.writeln('      out.add(${chunkNames[i]}[i] ^ ${padNames[i]}[i]);');
      buffer.writeln('    }');
    }
    buffer.writeln('    return out;');
    buffer.writeln('  }');
    buffer.writeln('}');

    return VaultKeyMaterial._(key, buffer.toString());
  }
}
