import 'dart:io';

import 'package:path/path.dart' as p;

/// Writes `lib/flutter_obfuscator/native_key_channel.g.dart`, the Dart
/// side of the v2 native key channel: fetches the vault key from
/// `ObfuscatorKeyPlugin` (Kotlin/Swift) instead of holding it in the Dart
/// snapshot as split constants.
class NativeKeyChannelGenerator {
  static void write({required String projectRoot}) {
    final dir = Directory(p.join(projectRoot, 'lib', 'flutter_obfuscator'));
    dir.createSync(recursive: true);
    File(p.join(dir.path, 'native_key_channel.g.dart'))
        .writeAsStringSync(_source());
  }

  static String _source() {
    return '''
// GENERATED BY flutter_obfuscator. DO NOT EDIT.
// ignore_for_file: type=lint

import 'dart:typed_data';

import 'package:flutter/services.dart';

/// Fetches the vault key from native code over a MethodChannel instead of
/// holding it in the Dart snapshot. See `ObfuscatorKeyPlugin.kt`
/// (Android) / `ObfuscatorKeyPlugin.swift` (iOS), generated alongside
/// this file's native counterparts.
class NativeKeyChannel {
  NativeKeyChannel._();

  static const MethodChannel _channel =
      MethodChannel('flutter_obfuscator/key');

  static Future<List<int>> fetchKey() async {
    final result = await _channel.invokeMethod<Uint8List>('getKey');
    if (result == null) {
      throw StateError(
        'NativeKeyChannel.fetchKey() got no key back from the native '
        'side. Make sure ObfuscatorKeyPlugin is registered in '
        'MainActivity.kt / AppDelegate.swift (see README) and that this '
        'run targets a platform flutter_obfuscator wired (Android/iOS).',
      );
    }
    return result;
  }
}
''';
  }
}
