import 'dart:io';

import 'package:path/path.dart' as p;

import '../crypto/key_strategy.dart';

/// Writes `lib/flutter_obfuscator/asset_vault.g.dart`, which decrypts
/// assets encrypted in place by [AssetEncryptor]. Shares the same key
/// source the secret vault uses (either `_obf_key_material.g.dart` or
/// `native_key_channel.g.dart`, per [KeyStrategy]), so both generators
/// must run against the same project with the same strategy.
class AssetVaultGenerator {
  static void write({
    required String projectRoot,
    required KeyStrategy keyStrategy,
  }) {
    final dir = Directory(p.join(projectRoot, 'lib', 'flutter_obfuscator'));
    dir.createSync(recursive: true);
    File(p.join(dir.path, 'asset_vault.g.dart'))
        .writeAsStringSync(_source(keyStrategy));
  }

  static String _source(KeyStrategy keyStrategy) {
    final isNative = keyStrategy.usesNativeChannel;
    final keyImport = isNative
        ? "import 'native_key_channel.g.dart';"
        : "import '_obf_key_material.g.dart';";
    final keyFetch = isNative
        ? 'final keyBytes = await NativeKeyChannel.fetchKey();'
        : 'final keyBytes = _ObfKeyMaterial.materialize();';
    final limitationDoc = isNative
        ? '/// v2: fetches the key from native code over a MethodChannel — see\n'
            "/// `SecretVault`'s doc comment for what that does and does not defend\n"
            '/// against.'
        : '/// v1 limitation: shares the same in-snapshot key material as\n'
            "/// `SecretVault` — see that file's doc comment for what this does and\n"
            '/// does not defend against.';

    return '''
// GENERATED BY flutter_obfuscator. DO NOT EDIT.
// ignore_for_file: type=lint

import 'dart:convert';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:flutter/services.dart' show rootBundle;

$keyImport

/// Loads assets that flutter_obfuscator encrypted in place at build
/// time. Drop-in replacement for the `rootBundle.load`/`loadString`
/// calls it was rewritten from.
///
$limitationDoc
class AssetVault {
  AssetVault._();

  static const List<int> _magic = [0x46, 0x4F, 0x42, 0x31]; // 'FOB1'

  static Future<Uint8List> load(String assetPath) async {
    final data = await rootBundle.load(assetPath);
    final bytes =
        data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);

    if (!_hasMagic(bytes)) {
      // Not one of ours (e.g. excluded by config) - return as-is.
      return bytes;
    }

    final nonceLen = bytes[4];
    final macLen = bytes[5];
    var offset = 6;
    final nonce = bytes.sublist(offset, offset + nonceLen);
    offset += nonceLen;
    final mac = bytes.sublist(offset, offset + macLen);
    offset += macLen;
    final cipherText = bytes.sublist(offset);

    $keyFetch
    final algorithm = AesGcm.with256bits();
    final box = SecretBox(cipherText, nonce: nonce, mac: Mac(mac));
    final clear =
        await algorithm.decrypt(box, secretKey: SecretKey(keyBytes));
    return Uint8List.fromList(clear);
  }

  static Future<String> loadString(String assetPath) async {
    final bytes = await load(assetPath);
    return utf8.decode(bytes);
  }

  static bool _hasMagic(Uint8List bytes) {
    if (bytes.length < 6) return false;
    for (var i = 0; i < _magic.length; i++) {
      if (bytes[i] != _magic[i]) return false;
    }
    return true;
  }
}
''';
  }
}
