import 'dart:io';

import 'package:path/path.dart' as p;

/// Writes `lib/flutter_obfuscator/asset_vault.g.dart`, which decrypts
/// assets encrypted in place by [AssetEncryptor]. Shares the same key
/// material file (`_obf_key_material.g.dart`) the secret vault writes,
/// so both generators must run against the same project.
class AssetVaultGenerator {
  static void write({required String projectRoot}) {
    final dir = Directory(p.join(projectRoot, 'lib', 'flutter_obfuscator'));
    dir.createSync(recursive: true);
    File(p.join(dir.path, 'asset_vault.g.dart')).writeAsStringSync(_source());
  }

  static String _source() {
    return '''
// GENERATED BY flutter_obfuscator. DO NOT EDIT.
// ignore_for_file: type=lint

import 'dart:convert';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:flutter/services.dart' show rootBundle;

import '_obf_key_material.g.dart';

/// Loads assets that flutter_obfuscator encrypted in place at build
/// time. Drop-in replacement for the `rootBundle.load`/`loadString`
/// calls it was rewritten from.
///
/// v1 limitation: shares the same in-snapshot key material as
/// `SecretVault` — see that file's doc comment for what this does and
/// does not defend against.
class AssetVault {
  AssetVault._();

  static const List<int> _magic = [0x46, 0x4F, 0x42, 0x31]; // 'FOB1'

  static Future<Uint8List> load(String assetPath) async {
    final data = await rootBundle.load(assetPath);
    final bytes =
        data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);

    if (!_hasMagic(bytes)) {
      // Not one of ours (e.g. excluded by config) - return as-is.
      return bytes;
    }

    final nonceLen = bytes[4];
    final macLen = bytes[5];
    var offset = 6;
    final nonce = bytes.sublist(offset, offset + nonceLen);
    offset += nonceLen;
    final mac = bytes.sublist(offset, offset + macLen);
    offset += macLen;
    final cipherText = bytes.sublist(offset);

    final keyBytes = _ObfKeyMaterial.materialize();
    final algorithm = AesGcm.with256bits();
    final box = SecretBox(cipherText, nonce: nonce, mac: Mac(mac));
    final clear =
        await algorithm.decrypt(box, secretKey: SecretKey(keyBytes));
    return Uint8List.fromList(clear);
  }

  static Future<String> loadString(String assetPath) async {
    final bytes = await load(assetPath);
    return utf8.decode(bytes);
  }

  static bool _hasMagic(Uint8List bytes) {
    if (bytes.length < 6) return false;
    for (var i = 0; i < _magic.length; i++) {
      if (bytes[i] != _magic[i]) return false;
    }
    return true;
  }
}
''';
  }
}
