import 'dart:io';

import 'package:path/path.dart' as p;

import '../crypto/key_material.dart';
import 'secret_finding.dart';

/// Writes the generated runtime files a staged project needs to resolve
/// `SecretVault.get(id)` calls left behind by [SecretScanner]:
///
/// - `lib/flutter_obfuscator/_obf_key_material.g.dart` (the split/XORed
///   key chunks — see [VaultKeyMaterial])
/// - `lib/flutter_obfuscator/secret_vault_data.g.dart` (id -> ciphertext)
/// - `lib/flutter_obfuscator/secret_vault.g.dart` (the public `SecretVault`
///   API: `init()` + `get(id)`)
class SecretVaultGenerator {
  static void write({
    required String projectRoot,
    required List<SecretFinding> findings,
    required VaultKeyMaterial keyMaterial,
  }) {
    final dir = Directory(p.join(projectRoot, 'lib', 'flutter_obfuscator'));
    dir.createSync(recursive: true);

    File(p.join(dir.path, '_obf_key_material.g.dart'))
        .writeAsStringSync(keyMaterial.generatedSource);

    File(p.join(dir.path, 'secret_vault_data.g.dart'))
        .writeAsStringSync(_dataFileSource(findings));

    File(p.join(dir.path, 'secret_vault.g.dart'))
        .writeAsStringSync(_vaultFileSource());
  }

  static String _dataFileSource(List<SecretFinding> findings) {
    final buffer = StringBuffer();
    buffer.writeln('// GENERATED BY flutter_obfuscator. DO NOT EDIT.');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln();
    buffer.writeln("class ObfEntry {");
    buffer.writeln('  const ObfEntry(this.nonce, this.cipherText, this.mac);');
    buffer.writeln('  final String nonce;');
    buffer.writeln('  final String cipherText;');
    buffer.writeln('  final String mac;');
    buffer.writeln('}');
    buffer.writeln();
    buffer.writeln('const Map<String, ObfEntry> secretVaultData = {');
    for (final f in findings) {
      buffer.writeln(
        "  '${f.id}': ObfEntry('${f.entry.nonceB64}', "
        "'${f.entry.cipherTextB64}', '${f.entry.macB64}'),",
      );
    }
    buffer.writeln('};');
    return buffer.toString();
  }

  static String _vaultFileSource() {
    return '''
// GENERATED BY flutter_obfuscator. DO NOT EDIT.
// ignore_for_file: type=lint

import 'dart:convert';

import 'package:cryptography/cryptography.dart';

import '_obf_key_material.g.dart';
import 'secret_vault_data.g.dart';

/// Runtime access to hardcoded secrets encrypted at build time by
/// flutter_obfuscator.
///
/// Call `await SecretVault.init()` once, before `runApp()`, then use
/// `SecretVault.get(id)` anywhere synchronously.
///
/// v1 limitation: the decryption key is reconstructed from split
/// constants inside this Dart snapshot (see `_obf_key_material.g.dart`).
/// That defeats a plain `strings`/grep static scan, but not a determined
/// reverse engineer with a decompiler or Frida attached at runtime.
/// A future version moves this key material into native code behind a
/// platform channel to close that gap.
class SecretVault {
  SecretVault._();

  static final Map<String, String> _decrypted = {};
  static bool _initialized = false;

  static Future<void> init() async {
    if (_initialized) return;
    final keyBytes = _ObfKeyMaterial.materialize();
    final algorithm = AesGcm.with256bits();
    final secretKey = SecretKey(keyBytes);

    for (final entry in secretVaultData.entries) {
      final box = SecretBox(
        base64Decode(entry.value.cipherText),
        nonce: base64Decode(entry.value.nonce),
        mac: Mac(base64Decode(entry.value.mac)),
      );
      final clear = await algorithm.decrypt(box, secretKey: secretKey);
      _decrypted[entry.key] = utf8.decode(clear);
    }
    _initialized = true;
  }

  static String get(String id) {
    if (!_initialized) {
      throw StateError(
        'SecretVault.get(\\'\$id\\') called before SecretVault.init(). '
        'Call `await SecretVault.init();` once in main() before runApp().',
      );
    }
    final value = _decrypted[id];
    if (value == null) {
      throw StateError('SecretVault: no entry for id "\$id".');
    }
    return value;
  }
}
''';
  }
}
