import 'dart:io';

import 'package:path/path.dart' as p;

import '../crypto/key_material.dart';
import '../crypto/key_strategy.dart';
import 'secret_finding.dart';

/// Writes the generated runtime files a staged project needs to resolve
/// `SecretVault.get(id)` calls left behind by [SecretScanner]:
///
/// - `lib/flutter_obfuscator/_obf_key_material.g.dart` (the split/XORed
///   key chunks — see [VaultKeyMaterial]) when [KeyStrategy.dartSplit]
/// - `lib/flutter_obfuscator/secret_vault_data.g.dart` (id -> ciphertext)
/// - `lib/flutter_obfuscator/secret_vault.g.dart` (the public `SecretVault`
///   API: `init()` + `get(id)`)
class SecretVaultGenerator {
  static void write({
    required String projectRoot,
    required List<SecretFinding> findings,
    required KeyStrategy keyStrategy,
    VaultKeyMaterial? keyMaterial,
  }) {
    final dir = Directory(p.join(projectRoot, 'lib', 'flutter_obfuscator'));
    dir.createSync(recursive: true);

    if (keyStrategy == KeyStrategy.dartSplit) {
      if (keyMaterial == null) {
        throw ArgumentError(
            'keyMaterial is required for KeyStrategy.dartSplit');
      }
      File(p.join(dir.path, '_obf_key_material.g.dart'))
          .writeAsStringSync(keyMaterial.generatedSource);
    }

    File(p.join(dir.path, 'secret_vault_data.g.dart'))
        .writeAsStringSync(_dataFileSource(findings));

    File(p.join(dir.path, 'secret_vault.g.dart'))
        .writeAsStringSync(_vaultFileSource(keyStrategy));
  }

  static String _dataFileSource(List<SecretFinding> findings) {
    final buffer = StringBuffer();
    buffer.writeln('// GENERATED BY flutter_obfuscator. DO NOT EDIT.');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln();
    buffer.writeln("class ObfEntry {");
    buffer.writeln('  const ObfEntry(this.nonce, this.cipherText, this.mac);');
    buffer.writeln('  final String nonce;');
    buffer.writeln('  final String cipherText;');
    buffer.writeln('  final String mac;');
    buffer.writeln('}');
    buffer.writeln();
    buffer.writeln('const Map<String, ObfEntry> secretVaultData = {');
    for (final f in findings) {
      buffer.writeln(
        "  '${f.id}': ObfEntry('${f.entry.nonceB64}', "
        "'${f.entry.cipherTextB64}', '${f.entry.macB64}'),",
      );
    }
    buffer.writeln('};');
    return buffer.toString();
  }

  static String _vaultFileSource(KeyStrategy keyStrategy) {
    final isNative = keyStrategy.usesNativeChannel;
    final keyImport = isNative
        ? "import 'native_key_channel.g.dart';"
        : "import '_obf_key_material.g.dart';";
    final keyFetch = isNative
        ? 'final keyBytes = await NativeKeyChannel.fetchKey();'
        : 'final keyBytes = _ObfKeyMaterial.materialize();';
    final limitationDoc = isNative
        ? '/// v2: the decryption key is fetched from native code (Kotlin/Swift)\n'
            '/// over a MethodChannel — see ObfuscatorKeyPlugin.kt/.swift. It is\n'
            '/// no longer part of the Dart snapshot, so Dart-snapshot-aware\n'
            '/// extraction tools no longer recover it; the key now has to be\n'
            '/// pulled from the native binary/DEX instead. This still does not\n'
            '/// stop a Frida-based dynamic attacker hooking this call at runtime.'
        : '/// v1 limitation: the decryption key is reconstructed from split\n'
            '/// constants inside this Dart snapshot (see `_obf_key_material.g.dart`).\n'
            '/// That defeats a plain `strings`/grep static scan, but not a determined\n'
            '/// reverse engineer with a decompiler or Frida attached at runtime.\n'
            '/// Set `key_strategy: native_channel` in obfuscator.yaml to move the\n'
            '/// key into native code instead.';

    return '''
// GENERATED BY flutter_obfuscator. DO NOT EDIT.
// ignore_for_file: type=lint

import 'dart:convert';

import 'package:cryptography/cryptography.dart';

$keyImport
import 'secret_vault_data.g.dart';

/// Runtime access to hardcoded secrets encrypted at build time by
/// flutter_obfuscator.
///
/// Call `await SecretVault.init()` once, before `runApp()`, then use
/// `SecretVault.get(id)` anywhere synchronously.
///
$limitationDoc
class SecretVault {
  SecretVault._();

  static final Map<String, String> _decrypted = {};
  static bool _initialized = false;

  static Future<void> init() async {
    if (_initialized) return;
    $keyFetch
    final algorithm = AesGcm.with256bits();
    final secretKey = SecretKey(keyBytes);

    for (final entry in secretVaultData.entries) {
      final box = SecretBox(
        base64Decode(entry.value.cipherText),
        nonce: base64Decode(entry.value.nonce),
        mac: Mac(base64Decode(entry.value.mac)),
      );
      final clear = await algorithm.decrypt(box, secretKey: secretKey);
      _decrypted[entry.key] = utf8.decode(clear);
    }
    _initialized = true;
  }

  static String get(String id) {
    if (!_initialized) {
      throw StateError(
        'SecretVault.get(\\'\$id\\') called before SecretVault.init(). '
        'Call `await SecretVault.init();` once in main() before runApp().',
      );
    }
    final value = _decrypted[id];
    if (value == null) {
      throw StateError('SecretVault: no entry for id "\$id".');
    }
    return value;
  }
}
''';
  }
}
